apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: edigleisonb/argocd-fullcycle
  newTag: ef1f67fc29192dea835e0decc5c4263ef5d8fc65
