apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: edigleisonb/argocd-fullcycle
  newTag: 160826854f7698b9d6e6e3a2ccf2795cf7808e63
